In [1]:
import torch
import numpy as np


/home/alan/miniconda3/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
X = torch.tensor([[1.0, -1.0], [1.0, -1.0]])


In [19]:
X = torch.tensor([[1, 0, 2], [2, 1, 0]])
X


tensor([[1, 0, 2],
        [2, 1, 0]])

In [18]:
y = torch.tensor([0, 2])
y


tensor([0, 2])

In [39]:
y.unsqueeze(1)


tensor([[0],
        [2]])

In [46]:
X == y.unsqueeze(1)


tensor([[False,  True, False],
        [ True, False, False]])